# Python API
apply python function to call the optimization and risk model APIs

In [265]:
# Input: Postman token 
test_token = '8732d840-1fcf-4f21-a92e-d4390dd88fc6'

In [92]:
import requests
import json
import pandas as pd

## Optimization API
feature argument - json format:
```json
{
   "alpha": "QES_LEAP_1_SCORE",
   "template" : "default",
   "portfolio" : "SP500",
   "startDate" : "2018-09-30",
   "endDate" : "2018-12-31",
   "freq" : "1me",
   "notionalValue" : 100000000,
   "baseCurrency" : "USD",
   "riskModel" : 
       {
         "universe": "SP500",
         "template" : "default"
       }
}
```

In [358]:
def optimization_call(postman_token, 
                      alpha = "QES_LEAP_1_SCORE", 
                      template = "default",
                      portfolio = "SP500",
                      startDate = "2018-08-30",
                      endDate = "2018-12-31",
                      freq = "1me", notionalValue = 100000000,
                      baseCurrency = "USD",
                      riskModel = '{\n        "universe": "SP500",\n        "template": "default"\n    }',
                      verbose = True, saveFlag = True, savePath = '.'):
    '''
    call the optimization API and generate the corresponding Postman UUID token, 
    fectch and save the optimal weights and summary into pandas dataframe type
    Inputs:
        alpha: signal
        portfolio: universe
        startDate: start trading date
        endDate: end trading date
        freq: trading frequency
        verbose: boolean value of whether display the running status
        saveFlag: boolean value of whether save the file 
        savePath: file path for saving data
    Outputs:
        dictionary contains the status of API calling, portfolio optimal weights and summary 
    '''
    # get the header & args 
    headers = {
    'Authorization': 'Basic aGphaW46aGphaW4xMjM=',
    'Content-Type': 'application/json',
    'Postman-Token': postman_token,
    'cache-control': 'no-cache',
    }
    args_data = '\n    "alpha": "{0}",\n    "template": "{1}",\n    "portfolio": "{2}",\n    "startDate": "{3}",\n    "endDate": "{4}",\n    '.format(alpha, template, portfolio, startDate, endDate)+ '"freq": "{}",\n    "notionalValue": {},\n    "baseCurrency": "{}",\n    '.format(freq, notionalValue, baseCurrency)+ '"riskModel": {}\n'.format(riskModel)
    args_data = '{' + args_data + '}'
    # derive the API token
    uid = token_access(args_data, headers, verbose= verbose)
    callFlag = True
    if uid is None:
        # unsuccessful call
        callFlag = False
    
    # accesss Weight
    df_weight = data_process(uid, headers, saveFlag=saveFlag, savePath=savePath)
    # access Summary 
    df_summary = data_process(uid, headers, feature= 'Summary', saveFlag=saveFlag, savePath=savePath)
    
    return {'status': callFlag, 'weight': df_weight, 'summary':df_summary}

* usage showcase

In [353]:
# Optimization results dictionary with default inputs
result_dic = optimization_call(test_token)

In [357]:
# Weights
result_dic['weight']

,DATE,ID,Sedol,Ticker,Company Name,Sector,Industry Group,Country,Currency,IssuerId,WEIGHT,None,None
259,2018-09-30,9KRRG25L84,BD0PJ08,COL,Inmobiliaria Colonial,SOCIMI,S.A.,60,6010,ES,50,C879264,0
322,2018-09-30,9NJJO3GPRZ,7025471,EGL,Mota-Engil,SGPS,S.A.,20,2010,PT,50,C2919357,0
363,2018-09-30,ZVVV283MPZ,5962934,SEM,Semapa - Sociedade de Investimento e Gestão,SGPS,S.A.,15,1510,PT,50,C7234215,0
490,2018-09-30,ZVVVKK0K1Z,5973992,SON,Sonae,SGPS,S.A.,30,3010,PT,50,C883119,0
633,2018-09-30,92VVWDL039,4657736,COR,Corticeira Amorim,S.G.P.S.,S.A.,15,1510,PT,50,C879790,0
745,2018-09-30,9NJJ1E2D1Z,B0B9GS5,NOS,NOS,S.G.P.S.,S.A.,25,2540,PT,50,C2313104,0
898,2018-09-30,48RRG62VW9,B01FLQ6,ACS,ACS,Actividades de Construcción y Servicios,S.A.,20,2010,ES,50,C780678,0
1106,2018-09-30,4JEY3OYPEZ,B13ZSL5,ALTR,Altri,S.G.P.S.,S.A.,15,1510,PT,50,C20783030,0.00107831044156835
1176,2018-09-30,ZWL8D1KWM9,B18S767,BME,Bolsas y Mercados Españoles,Sociedad Holding de Mercados y Sistemas Finan...,S.A.,40,4020,ES,50,C22563601,0
1216,2018-09-30,Z562NQ31K9,B1FW751,GALP,Galp Energia,SGPS,S.A.,10,1010,PT,50,C874537,0
1451,2018-09-30,ZVVL661O3Z,B1Y1SQ7,JMT,Jerónimo Martins,SGPS,S.A.,30,3010,PT,50,C878246,0
1471,2018-09-30,4JE1LEO2YZ,B233HR5,RENE,REN - Redes Energéticas Nacionais,SGPS,S.A.,55,5510,PT,50,C5468837,0
1829,2018-10-31,9KRRG25L84,BD0PJ08,COL,Inmobiliaria Colonial,SOCIMI,S.A.,60,6010,ES,50,C879264,0
1892,2018-10-31,9NJJO3GPRZ,7025471,EGL,Mota-Engil,SGPS,S.A.,20,2010,PT,50,C2919357,0
1933,2018-10-31,ZVVV283MPZ,5962934,SEM,Semapa - Sociedade de Investimento e Gestão,SGPS,S.A.,15,1510,PT,50,C7234215,0
2060,2018-10-31,ZVVVKK0K1Z,5973992,SON,Sonae,SGPS,S.A.,30,3010,PT,50,C883119,0
2203,2018-10-31,92VVWDL039,4657736,COR,Corticeira Amorim,S.G.P.S.,S.A.,15,1510,PT,50,C879790,0
2315,2018-10-31,9NJJ1E2D1Z,B0B9GS5,NOS,NOS,S.G.P.S.,S.A.,50,5020,PT,50,C2313104,0
2468,2018-10-31,48RRG62VW9,B01FLQ6,ACS,ACS,Actividades de Construcción y Servicios,S.A.,20,2010,ES,50,C780678,0
2676,2018-10-31,4JEY3OYPEZ,B13ZSL5,ALTR,Altri,S.G.P.S.,S.A.,15,1510,PT,50,C20783030,0.00153533099267881
2746,2018-10-31,ZWL8D1KWM9,B18S767,BME,Bolsas y Mercados Españoles,Sociedad Holding de Mercados y Sistemas Finan...,S.A.,40,4020,ES,50,C22563601,0
2786,2018-10-31,Z562NQ31K9,B1FW751,GALP,Galp Energia,SGPS,S.A.,10,1010,PT,50,C874537,0
3021,2018-10-31,ZVVL661O3Z,B1Y1SQ7,JMT,Jerónimo Martins,SGPS,S.A.,30,3010,PT,50,C878246,0
3041,2018-10-31,4JE1LEO2YZ,B233HR5,RENE,REN - Redes Energéticas Nacionais,SGPS,S.A.,55,5510,PT,50,C5468837,0
3399,2018-11-30,9KRRG25L84,BD0PJ08,COL,Inmobiliaria Colonial,SOCIMI,S.A.,60,6010,ES,50,C879264,0
3462,2018-11-30,9NJJO3GPRZ,7025471,EGL,Mota-Engil,SGPS,S.A.,20,2010,PT,50,C2919357,0
3503,2018-11-30,ZVVV283MPZ,5962934,SEM,Semapa - Sociedade de Investimento e Gestão,SGPS,S.A.,15,1510,PT,50,C7234215,0
3630,2018-11-30,ZVVVKK0K1Z,5973992,SON,Sonae,SGPS,S.A.,30,3010,PT,50,C883119,0
3773,2018-11-30,92VVWDL039,4657736,COR,Corticeira Amorim,S.G.P.S.,S.A.,15,1510,PT,50,C879790,0
3885,2018-11-30,9NJJ1E2D1Z,B0B9GS5,NOS,NOS,S.G.P.S.,S.A.,50,5020,PT,50,C2313104,0
4038,2018-11-30,48RRG62VW9,B01FLQ6,ACS,ACS,Actividades de Construcción y Servicios,S.A.,20,2010,ES,50,C780678,0
4246,2018-11-30,4JEY3OYPEZ,B13ZSL5,ALTR,Altri,S.G.P.S.,S.A.,15,1510,PT,50,C20783030,0.00119971872331545
4316,2018-11-30,ZWL8D1KWM9,B18S767,BME,Bolsas y Mercados Españoles,Sociedad Holding de Mercados y Sistemas Finan...,S.A.,40,4020,ES,50,C22563601,0
4356,2018-11-30,Z562NQ31K9,B1FW751,GALP,Galp Energia,SGPS,S.A.,10,1010,PT,50,C874537,0
4591,2018-11-30,ZVVL661O3Z,B1Y1SQ7,JMT,Jerónimo Martins,SGPS,S.A.,30,3010,PT,50,C878246,0
4611,2018-11-30,4JE1LEO2YZ,B233HR5,RENE,REN - Redes Energéticas Nacionais,SGPS,S.A.,55,5510,PT,50,C5468837,0
4969,2018-12-31,9KRRG25L84,BD0PJ08,COL,Inmobiliaria Colonial,SOCIMI,S.A.,60,6010,ES,50,C879264,0.00363342494497137
5032,2018-12-31,9NJJO3GPRZ,7025471,EGL,Mota-Engil,SGPS,S.A.,20,2010,PT,50,C2919357,0
5073,2018-12-31,ZVVV283MPZ,5962934,SEM,Semapa - Sociedade de Investimento e Gestão,SGPS,S.A.,15,1510,PT,50,C7234215,0
5200,2018-12-31,ZVVVKK0K1Z,5973992,SON,Sonae,SGPS,S.A.,30,3010,PT,50,C883119,0
5343,2018-12-31,92VVWDL039,4657736,COR,Corticeira Amorim,S.G.P.S.,S.A.,15,1510,PT,50,C879790,0
5455,2018-12-31,9NJJ1E2D1Z,B0B9GS5,NOS,NOS,S.G.P.S.,S.A.,50,5020,PT,50,C2313104,0.00125569871344051
5608,2018-12-31,48RRG62VW9,B01FLQ6,ACS,ACS,Actividades de Construcción y Servicios,S.A.,20,2010,ES,50,C780678,0
5816,2018-12-31,4JEY3OYPEZ,B13ZSL5,ALTR,Altri,S.G.P.S.,S.A.,15,1510,PT,50,C20783030,0.00156808897593824
5886,2018-12-31,ZWL8D1KWM9,B18S767,BME,Bolsas y Mercados Españoles,Sociedad Holding de Mercados y Sistemas Finan...,S.A.,40,4020,ES,50,C22563601,0
5926,2018-12-31,Z562NQ31K9,B1FW751,GALP,Galp Energia,SGPS,S.A.,10,1010,PT,50,C874537,0
6161,2018-12-31,ZVVL661O3Z,B1Y1SQ7,JMT,Jerónimo Martins,SGPS,S.A.,30,3010,PT,50,C878246,0
6181,2018-12-31,4JE1LEO2YZ,B233HR5,RENE,REN - Redes Energéticas Nacionais,SGPS,S.A.,55,5510,PT,50,C5468837,0

In [234]:
# Summary
result_dic['summary']

,Alpha,Ex-Ante Risk,Ex-Ante Tracking Error,Turnover,Max Turnover
1,0.34771553678194,0.0975385350142646,0.0975385350142646,1.99999962340783,NA
2,0.355137553618081,0.107704547829215,0.107704547829215,1.44999721432476,NA
3,0.288000411658759,0.104215536770768,0.104215536770768,1.49999918674998,NA
4,0.24134166758503,0.0971503585210817,0.0971503585210817,1.49654598552549,NA

#### Inner Tool Function
* token_access

In [253]:
# init a Postman headers and optimization argument for fetch the data
headers = {'Authorization': 'Basic aGphaW46aGphaW4xMjM=','Content-Type': 'application/json','Postman-Token': '8732d840-1fcf-4f21-a92e-d4390dd88fc6','cache-control': 'no-cache'}

data = '{\n    "alpha": "QES_LEAP_1_SCORE",\n    "template": "default",\n    "portfolio": "SP500",\n    "startDate": "2018-08-30",\n    "endDate": "2018-12-31",\n    "freq": "1me",\n    "notionalValue": 100000000,\n    "baseCurrency": "USD",\n    "riskModel": {\n        "universe": "SP500",\n        "template": "default"\n    }\n}'

In [254]:
def token_access(args_data, headers, function = 'optimization', verbose = True):
    ''' 
    access the token for accessing the API results
    Input:
        args_data: feature with each value 
        function: {optimization|risk}
        verbose: boolean value to display the argument or not
    Output:
        unique id
    '''
    # call the 
    response = requests.post('http://feed.luoquant.com/{}/'.format(function),
                             headers=headers, data=data)
    if response.status_code == 200:
        return response.text
    
    if verbose:
        print('Unsuccessful call')
    return None

In [359]:
# Example : generate uid
uid =  token_access(data, headers)
print(uid)

32408e34-8ebe-4880-b2f0-2c6d4733c223

* data_process

In [197]:
def data_process(uid, headers, feature = 'Weights', function = 'optimization', saveFlag = True, savePath = '.'):
    # I. get the data content 
    response = requests.get('http://feed.luoquant.com/{0}/{1}/{2}.csv'.format(function, uid, feature),
                            headers=headers)
    data_text = response.text 
    
    # II. generate the corresponding pandas df
    df_raw = pd.DataFrame([[word.replace("\"", "") for word in line.split(',')] for line in data_text.split('\n')])
    # process the data df
    df = df_raw.rename(columns=df_raw.iloc[0]).iloc[1:]
    # drop the all-none value
    df.dropna(inplace = True)
    # III. save the data into local path with csv format
    if saveFlag:
        # by default save into the current directory
        df.to_csv(savePath + '/{}.csv'.format(feature))
    
    return df

In [363]:
# Example : generate and save the Weights data
df_weight = data_process(uid, headers)

df_weight.head()

,DATE,ID,Sedol,Ticker,Company Name,Sector,Industry Group,Country,Currency,IssuerId,WEIGHT,None,None
259,2018-09-30,9KRRG25L84,BD0PJ08,COL,Inmobiliaria Colonial,SOCIMI,S.A.,60,6010,ES,50,C879264,0
322,2018-09-30,9NJJO3GPRZ,7025471,EGL,Mota-Engil,SGPS,S.A.,20,2010,PT,50,C2919357,0
363,2018-09-30,ZVVV283MPZ,5962934,SEM,Semapa - Sociedade de Investimento e Gestão,SGPS,S.A.,15,1510,PT,50,C7234215,0
490,2018-09-30,ZVVVKK0K1Z,5973992,SON,Sonae,SGPS,S.A.,30,3010,PT,50,C883119,0
633,2018-09-30,92VVWDL039,4657736,COR,Corticeira Amorim,S.G.P.S.,S.A.,15,1510,PT,50,C879790,0

## Risk API
feature argument - json format:
```json
{
"universe": "SP500",
"template": "default",
"startDate": "2018-09-30",
"endDate": "2018-11-30",
"freq": "1me"
}
```
to be developed...